server:
  port: 8080
  servlet:
    encoding:
      charset: utf-8
      force: true

spring:
  mail:
    host: smtp.naver.com
    port: 465
    username: ${email.username}
    password: ${email.password}
    properties:
      mail.smtp.auth: true
      mail.smtp.ssl.enable: true
      mail.smtp.ssl.trust: smtp.naver.com

  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    hibernate:
      ddl-auto: update

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/${database.name}
    username: ${mysql.username}
    password: ${mysql.password}

  data:
    redis:
      host: localhost
      port: 6379

jwt:
  secret:
    key: ${jwt.secret.key}






